### ISSUE TITLE
Request — Open automatically?

### ISSUE THREAD

**Issue by megaroeny** [neversitdull/Open-Figma-Desktop#2]
Is it possible if openings links could be opened automatically?

**Comment by neversitdull** [comment]
I'd love to be able to do this, although it may have to be built directly into Figma. I'll try and do some research though on if I can detect a url on-click vs checking the clipboard.

**Comment by megaroeny** [comment]
Josh, it's you!! 😆 Awesome no worries man. This is super helpful already. Thanks!

**Comment by neversitdull** [comment]
We now have this as native functionality within Figma. 

https://www.figma.com/blog/figma-desktop-app-improvements/

**Comment by neversitdull** [comment]
We now have this as native functionality within Figma.

https://www.figma.com/blog/figma-desktop-app-improvements/
